apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-kotlin-template
  annotations:
    github.com/project-slug: 'backstage/backstage'
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
